<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pinba.proto

namespace Pinba;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>Pinba.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string hostname = 1;</code>
     */
    private $hostname = '';
    /**
     * Generated from protobuf field <code>string server_name = 2;</code>
     */
    private $server_name = '';
    /**
     * Generated from protobuf field <code>string script_name = 3;</code>
     */
    private $script_name = '';
    /**
     * Generated from protobuf field <code>uint32 request_count = 4;</code>
     */
    private $request_count = 0;
    /**
     * Generated from protobuf field <code>uint32 document_size = 5;</code>
     */
    private $document_size = 0;
    /**
     * Generated from protobuf field <code>uint32 memory_peak = 6;</code>
     */
    private $memory_peak = 0;
    /**
     * Generated from protobuf field <code>float request_time = 7;</code>
     */
    private $request_time = 0.0;
    /**
     * Generated from protobuf field <code>float ru_utime = 8;</code>
     */
    private $ru_utime = 0.0;
    /**
     * Generated from protobuf field <code>float ru_stime = 9;</code>
     */
    private $ru_stime = 0.0;
    /**
     * Generated from protobuf field <code>repeated uint32 timer_hit_count = 10;</code>
     */
    private $timer_hit_count;
    /**
     * Generated from protobuf field <code>repeated float timer_value = 11;</code>
     */
    private $timer_value;
    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_count = 12;</code>
     */
    private $timer_tag_count;
    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_name = 13;</code>
     */
    private $timer_tag_name;
    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_value = 14;</code>
     */
    private $timer_tag_value;
    /**
     * Generated from protobuf field <code>repeated string dictionary = 15;</code>
     */
    private $dictionary;
    /**
     * Generated from protobuf field <code>uint32 status = 16;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>uint32 memory_footprint = 17;</code>
     */
    private $memory_footprint = 0;
    /**
     * Generated from protobuf field <code>repeated .Pinba.Request requests = 18;</code>
     */
    private $requests;
    /**
     * Generated from protobuf field <code>string schema = 19;</code>
     */
    private $schema = '';
    /**
     * Generated from protobuf field <code>repeated uint32 tag_name = 20;</code>
     */
    private $tag_name;
    /**
     * Generated from protobuf field <code>repeated uint32 tag_value = 21;</code>
     */
    private $tag_value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hostname
     *     @type string $server_name
     *     @type string $script_name
     *     @type int $request_count
     *     @type int $document_size
     *     @type int $memory_peak
     *     @type float $request_time
     *     @type float $ru_utime
     *     @type float $ru_stime
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $timer_hit_count
     *     @type float[]|\Google\Protobuf\Internal\RepeatedField $timer_value
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $timer_tag_count
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $timer_tag_name
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $timer_tag_value
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $dictionary
     *     @type int $status
     *     @type int $memory_footprint
     *     @type \Pinba\Request[]|\Google\Protobuf\Internal\RepeatedField $requests
     *     @type string $schema
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $tag_name
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $tag_value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pinba::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string hostname = 1;</code>
     * @return string
     */
    public function getHostname()
    {
        return $this->hostname;
    }

    /**
     * Generated from protobuf field <code>string hostname = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHostname($var)
    {
        GPBUtil::checkString($var, True);
        $this->hostname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string server_name = 2;</code>
     * @return string
     */
    public function getServerName()
    {
        return $this->server_name;
    }

    /**
     * Generated from protobuf field <code>string server_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setServerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->server_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string script_name = 3;</code>
     * @return string
     */
    public function getScriptName()
    {
        return $this->script_name;
    }

    /**
     * Generated from protobuf field <code>string script_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setScriptName($var)
    {
        GPBUtil::checkString($var, True);
        $this->script_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 request_count = 4;</code>
     * @return int
     */
    public function getRequestCount()
    {
        return $this->request_count;
    }

    /**
     * Generated from protobuf field <code>uint32 request_count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRequestCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->request_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 document_size = 5;</code>
     * @return int
     */
    public function getDocumentSize()
    {
        return $this->document_size;
    }

    /**
     * Generated from protobuf field <code>uint32 document_size = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDocumentSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->document_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 memory_peak = 6;</code>
     * @return int
     */
    public function getMemoryPeak()
    {
        return $this->memory_peak;
    }

    /**
     * Generated from protobuf field <code>uint32 memory_peak = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMemoryPeak($var)
    {
        GPBUtil::checkUint32($var);
        $this->memory_peak = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float request_time = 7;</code>
     * @return float
     */
    public function getRequestTime()
    {
        return $this->request_time;
    }

    /**
     * Generated from protobuf field <code>float request_time = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setRequestTime($var)
    {
        GPBUtil::checkFloat($var);
        $this->request_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float ru_utime = 8;</code>
     * @return float
     */
    public function getRuUtime()
    {
        return $this->ru_utime;
    }

    /**
     * Generated from protobuf field <code>float ru_utime = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setRuUtime($var)
    {
        GPBUtil::checkFloat($var);
        $this->ru_utime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float ru_stime = 9;</code>
     * @return float
     */
    public function getRuStime()
    {
        return $this->ru_stime;
    }

    /**
     * Generated from protobuf field <code>float ru_stime = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setRuStime($var)
    {
        GPBUtil::checkFloat($var);
        $this->ru_stime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_hit_count = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTimerHitCount()
    {
        return $this->timer_hit_count;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_hit_count = 10;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTimerHitCount($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->timer_hit_count = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float timer_value = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTimerValue()
    {
        return $this->timer_value;
    }

    /**
     * Generated from protobuf field <code>repeated float timer_value = 11;</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTimerValue($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->timer_value = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_count = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTimerTagCount()
    {
        return $this->timer_tag_count;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_count = 12;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTimerTagCount($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->timer_tag_count = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_name = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTimerTagName()
    {
        return $this->timer_tag_name;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_name = 13;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTimerTagName($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->timer_tag_name = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_value = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTimerTagValue()
    {
        return $this->timer_tag_value;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_value = 14;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTimerTagValue($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->timer_tag_value = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string dictionary = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDictionary()
    {
        return $this->dictionary;
    }

    /**
     * Generated from protobuf field <code>repeated string dictionary = 15;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDictionary($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->dictionary = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 16;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 memory_footprint = 17;</code>
     * @return int
     */
    public function getMemoryFootprint()
    {
        return $this->memory_footprint;
    }

    /**
     * Generated from protobuf field <code>uint32 memory_footprint = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setMemoryFootprint($var)
    {
        GPBUtil::checkUint32($var);
        $this->memory_footprint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Pinba.Request requests = 18;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRequests()
    {
        return $this->requests;
    }

    /**
     * Generated from protobuf field <code>repeated .Pinba.Request requests = 18;</code>
     * @param \Pinba\Request[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRequests($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pinba\Request::class);
        $this->requests = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string schema = 19;</code>
     * @return string
     */
    public function getSchema()
    {
        return $this->schema;
    }

    /**
     * Generated from protobuf field <code>string schema = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setSchema($var)
    {
        GPBUtil::checkString($var, True);
        $this->schema = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 tag_name = 20;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTagName()
    {
        return $this->tag_name;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 tag_name = 20;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTagName($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->tag_name = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 tag_value = 21;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTagValue()
    {
        return $this->tag_value;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 tag_value = 21;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTagValue($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->tag_value = $arr;

        return $this;
    }

}

